probe:
  image: weaveworks/scope:0.13.1
  net: "host"
  pid: "host"
  privileged: true
  labels:
    - "works.weave.role=system"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:rw"
  command:
    - "--probe.docker"
    - "true"
    - "--service-token"
    - "MY_SCOPE_SERVICE_TOKEN" 