client:
  build: client
  links:
    - qotd
    - pyapp
pyapp:
  build: pyapp
  ports:
    - "5000"
  links:
    - qotd
    - redis
    - goapp
qotd:
  build: qotd
  expose:
    - "4446"
redis:
  image: redis
goapp:
  build: goapp
  ports:
    - "8080"
  links:
    - elasticsearch1
    - elasticsearch2
elasticsearch1:
  image: elasticsearch
  expose:
    - "9200"
    - "9300"
elasticsearch2:
  image: elasticsearch
  expose:
    - "9200"
    - "9300"
  links:
    - elasticsearch1
