client:
  build: client
  links:
    - qotd
    - pyapp1
    - pyapp2
pyapp1:
  build: pyapp
  expose:
    - "5000"
  links:
    - qotd
    - redis
    - goapp1
    - goapp2
pyapp2:
  build: pyapp
  expose:
    - "5000"
  links:
    - qotd
    - redis
    - goapp1
    - goapp2
qotd:
  build: qotd
  expose:
    - "4446"
redis:
  image: redis
goapp1:
  build: goapp
  expose:
    - "8080"
  links:
    - elasticsearch1
    - elasticsearch2
    - elasticsearch3
goapp2:
  build: goapp
  expose:
    - "8080"
  links:
    - elasticsearch1
    - elasticsearch2
    - elasticsearch3
elasticsearch1:
  image: elasticsearch
  expose:
    - "9200"
    - "9300"
elasticsearch2:
  image: elasticsearch
  expose:
    - "9200"
    - "9300"
  links:
    - elasticsearch1
elasticsearch3:
  image: elasticsearch
  expose:
    - "9200"
    - "9300"
  links:
    - elasticsearch1
    - elasticsearch2
